import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, CheckCheck, ChevronRight, CircleHelp, ClipboardCheck, Clock3, FileText, FolderClosed, FolderOpen, History, Layers3, Link2, LoaderCircle, PackageCheck, Plus, RotateCcw, X, AlertCircle, FlaskConical, Wrench, GitCompareArrows, ExternalLink, ShieldCheck, CheckCircle2, Menu } from 'lucide-react';
import type { Action, DemoState, DocumentData, LabAction, OfferAction, ServiceAction, Stage } from './types';
import { getDocuments } from './documentContent';
import HelpSection from './HelpSection';
import ServiceScenario from './ServiceScenario';
import OfferScenario from './OfferScenario';
import LabScenario from './LabScenario';

type Panel = { kind: 'document'; id: string } | { kind: 'action'; action: Action } | { kind: 'compare' } | { kind: 'help' } | { kind: 'reset' } | null;
const stageOrder: Stage[] = ['change', 'implementation', 'testing', 'remediation', 'retesting', 'preparation', 'delivered'];
const stageNames: Record<Stage, string> = { change: 'Modificare de analizat', implementation: 'Execuție', testing: 'Testare', remediation: 'Remediere', retesting: 'Retestare', preparation: 'Pregătire predare', delivered: 'Predată' };
const actionTitles: Record<Action, string> = { 'accept-change': 'Acceptă modificarea în simulare', implement: 'Consemnează implementarea', 'run-test': 'Înregistrează testul', remediate: 'Înregistrează remedierea', retest: 'Confirmă retestarea', 'attach-test': 'Atașează fișa de test', 'attach-manual': 'Atașează instrucțiunile rev. 02', handover: 'Finalizează predarea demonstrativă' };
const workCopy: Record<Stage, { eyebrow: string; title: string; text: string; action?: Action; button: string; icon: typeof FileText }> = {
  change: { eyebrow: '01 / DECIZIE', title: 'Două stări, fără ambiguități.', text: 'Beneficiarul solicită afișarea distinctă a stărilor „Funcționare” și „Indisponibil”. Urmărește schimbarea de la cerință până la predare.', action: 'accept-change', button: 'Analizează modificarea', icon: GitCompareArrows },
  implementation: { eyebrow: '02 / IMPLEMENTARE', title: 'Revizia nouă ajunge la execuție.', text: 'Cerințele, lista semnalelor și fișa de test sunt la revizia 02. Sarcina de implementare este pregătită pentru responsabilul demonstrativ.', action: 'implement', button: 'Consemnează implementarea', icon: Wrench },
  testing: { eyebrow: '03 / TESTARE', title: 'Verificăm legătura cu cerințele.', text: 'Implementarea a fost consemnată. Testul demonstrativ compară etichetele interfeței cu cerințele acceptate și instrucțiunile operatorului.', action: 'run-test', button: 'Deschide fișa de test', icon: FlaskConical },
  remediation: { eyebrow: '04 / OBSERVAȚIE DESCHISĂ', title: 'O etichetă mai are de parcurs un pas.', text: 'Pentru starea „Indisponibil”, interfața păstrează denumirea anterioară. Observația DEMO-OBS-001 leagă testul de sarcina de remediere.', action: 'remediate', button: 'Consemnează remedierea', icon: AlertCircle },
  retesting: { eyebrow: '05 / RETESTARE', title: 'Remediată. Acum, de verificat.', text: 'Dovada demonstrativă a fost înregistrată. Observația rămâne deschisă până când retestarea confirmă corespondența cu revizia 02.', action: 'retest', button: 'Deschide retestarea', icon: FlaskConical },
  preparation: { eyebrow: '06 / PACHET DE PREDARE', title: 'Rezultatele sunt gata. Reunim dosarul.', text: 'Observația este închisă prin retestare. Adaugă explicit fișa de test și instrucțiunile finale în pachetul care va fi predat.', button: 'Verifică pachetul', icon: PackageCheck },
  delivered: { eyebrow: '07 / TRASEU ÎNCHEIAT', title: 'Un dosar complet. O poveste clară.', text: 'Pachetul demonstrativ păstrează documentele și reviziile transmise. Fiecare pas poate fi urmărit în istoric, de la schimbare până la predare.', button: 'Vezi procesul-verbal', icon: CheckCheck },
};

function formatTime(value: string) { return new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function formatDate(value: string) { return new Intl.DateTimeFormat('ro-RO', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}><span />{children}</span>; }

function CabinetIllustration({ revision = 1 }: { revision?: number }) {
  return <div className="cabinet-art" aria-label="Ilustrație conceptuală a unui tablou de automatizare, fără specificații tehnice" role="img">
    <div className="art-grid" /><div className="art-orbit" />
    <svg className="cabinet-svg" viewBox="0 0 360 340" fill="none" aria-hidden="true">
      <defs><linearGradient id="cabinet" x1="60" y1="20" x2="300" y2="300" gradientUnits="userSpaceOnUse"><stop stopColor="#fff"/><stop offset="1" stopColor="#e3e6e3"/></linearGradient><linearGradient id="side" x1="270" y1="0" x2="320" y2="0"><stop stopColor="#bdc5c2"/><stop offset="1" stopColor="#e3e6e3"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="15" stdDeviation="10" floodOpacity=".12"/></filter></defs>
      <ellipse cx="185" cy="310" rx="116" ry="17" fill="#243e35" opacity=".07" />
      <g filter="url(#shadow)"><path d="M86 45 260 29 292 50 292 282 114 309 86 285Z" fill="url(#side)" stroke="#bcc4c0"/><path d="M86 45 260 29 260 269 86 285Z" fill="url(#cabinet)" stroke="#c3ccc6"/><path d="M98 58 247 44 247 256 98 271Z" stroke="#bac4bf"/><path d="M104 64 241 51" stroke="white" strokeWidth="2"/>
      <path d="M123 94 216 85 216 151 123 160Z" fill="#263d36"/><path d="M130 100 209 93 209 143 130 151Z" fill="#526960"/>
      <path d="M142 112 187 108M142 120 177 116" stroke="#91b0a0" strokeWidth="3"/><path d="M142 136 161 134" stroke="#c9dccb" strokeWidth="5"/><circle cx="197" cy="131" r="4" fill="#bcd3bd"/>
      <path d="M123 177 215 168" stroke="#c8cfca"/><ellipse cx="139" cy="191" rx="7" ry="8" fill="#82988a"/><ellipse cx="163" cy="189" rx="7" ry="8" fill="#bcbcab"/><ellipse cx="188" cy="186" rx="7" ry="8" fill="#c55346"/>
      <path d="M126 233 190 227M126 239 190 233M126 245 190 239" stroke="#b1bdb5" strokeWidth="2"/><path d="M229 172 229 193" stroke="#819088" strokeWidth="5" strokeLinecap="round"/><path d="M270 62 279 68 279 259 270 263" stroke="#a7b2ab"/>
      <path d="M129 281 129 301M239 270 239 286" stroke="#899a8e" strokeWidth="4"/></g>
      <path d="M69 89H35V151H65M283 164H324V220H298" stroke="#c98a7f" strokeDasharray="3 4"/><circle cx="69" cy="89" r="3" fill="#ba4b3c"/><circle cx="298" cy="220" r="3" fill="#ba4b3c"/>
    </svg>
    <div className="art-label label-top"><span className="tiny-square" />DEMO-TA-001 <span className="muted">/</span> AUTOMATIZARE</div>
    <div className="art-label label-bottom"><Layers3 size={14} /> Revizia 0{revision}<span className="art-check"><Check size={11} /></span></div>
    <span className="art-caption">ILUSTRAȚIE CONCEPTUALĂ</span>
  </div>;
}

function Modal({ title, eyebrow, children, onClose, wide = false }: { title: string; eyebrow: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => {
    const last = document.activeElement as HTMLElement | null;
    const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden';
    ref.current?.focus();
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeRef.current();
      if (e.key === 'Tab') {
        const items = ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input, summary, [tabindex="0"]');
        if (!items?.length) return;
        const first = items[0], lastItem = items[items.length - 1];
        if (e.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { e.preventDefault(); lastItem.focus(); }
        else if (!e.shiftKey && (document.activeElement === lastItem || document.activeElement === ref.current)) { e.preventDefault(); first.focus(); }
      }
    };
    document.addEventListener('keydown', handler);
    return () => { document.body.style.overflow = overflow; document.removeEventListener('keydown', handler); last?.focus(); };
  }, []);
  return <div className="modal-backdrop" onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div ref={ref} tabIndex={-1} className={`modal ${wide ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><header className="modal-header"><div><p className="eyebrow">{eyebrow}</p><h2 id="modal-title">{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Închide panoul"><X size={21}/></button></header>{children}</div></div>;
}

function RevisionComparison({ accepted }: { accepted: boolean }) {
  return <div className="revision-compare"><div className="revision-column previous"><div className="comparison-label">REVIZIA 01 <Badge>{accepted ? 'Înlocuită' : 'Valabilă acum'}</Badge></div><h3>Denumirea anterioară</h3><p className="state-label">Funcționare</p><p className="state-label removed">Oprit <span>−</span></p><p className="small muted">„Oprit” este o completare fictivă pentru comparație.</p></div><div className="revision-column next"><div className="comparison-label">REVIZIA 02 <Badge tone="green">{accepted ? 'Valabilă' : 'Propusă'}</Badge></div><h3>Denumirile solicitate</h3><p className="state-label">Funcționare</p><p className="state-label added">Indisponibil <Plus size={14}/></p><p className="small muted">Două stări distincte pentru echipamentul demonstrativ P-01.</p></div></div>;
}

function DocumentViewer({ doc, state, openCompare }: { doc: DocumentData; state: DemoState; openCompare: () => void }) {
  return <div className="document-body"><div className="document-meta"><span className="mono">{doc.code}</span><Badge>Revizia {doc.revision}</Badge><Badge tone={doc.status.toLowerCase().includes('proiect') ? 'amber' : 'green'}>{doc.status}</Badge></div><div className="document-notice">DOCUMENT SIMULAT · Nu reprezintă documentație tehnică pentru execuție sau conformitate.</div><p className="document-lead">{doc.lead}</p>{doc.id === 'requirements' && <button className="button secondary" onClick={openCompare}><GitCompareArrows size={16}/> Compară reviziile 01 și 02</button>}{doc.sections.map((section, i) => <section className="document-section" key={i}><h3>{section.title}</h3>{section.body && <p>{section.body}</p>}{section.rows && <div className="table-scroll"><table>{section.headers && <thead><tr>{section.headers.map((h,j) => <th key={j}>{h}</th>)}</tr></thead>}<tbody>{section.rows.map((row,j) => <tr key={j}>{row.map((cell,k) => <td key={k}>{cell}</td>)}</tr>)}</tbody></table></div>}</section>)}{doc.id === 'test' && state.observation && state.observation.status !== 'open' && <Evidence/>}<div className="document-end"><span>ICPE Bistrița · Dosar DEMO-L-001</span><span>Date și proceduri fictive</span></div></div>;
}

function Evidence() { return <div className="evidence"><div><span className="eyebrow">DOVADĂ DEMONSTRATIVĂ</span><h3>Eticheta după actualizare</h3><p className="small muted">Reprezentare schematică, fără conexiune la un echipament.</p></div><div className="mock-hmi"><span>P-01 / PREVIZUALIZARE</span><strong><span/>Indisponibil</strong><small>Conform cerinței fictive · rev. 02</small></div></div>; }

export default function App() {
  const [state, setState] = useState<DemoState | null>(null);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [view, setView] = useState<'overview' | 'dossier' | 'service' | 'offer' | 'lab'>('overview');
  const [tab, setTab] = useState<'work' | 'documents' | 'history'>('work');
  const [panel, setPanel] = useState<Panel>(null); const [toast, setToast] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 4800); return () => window.clearTimeout(timer); }, [toast]);
  async function load() { try { const res = await fetch('/api/state'); if (!res.ok) throw new Error('API-ul local nu a răspuns.'); const data = await res.json(); setState(data); setError(''); } catch { setError('Nu putem încărca dosarul. Verifică dacă API-ul local este pornit, apoi reîncearcă.'); } }
  async function mutate(action?: Action | ServiceAction | OfferAction | LabAction): Promise<boolean> {
    if (busy) return false; setBusy(true); setError('');
    try {
      const response = await fetch(action ? '/api/actions' : '/api/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(action ? { type: action } : {}) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Acțiunea nu a putut fi salvată.');
      setState(data); setPanel(null); setToast(action ? (action.startsWith('service-') ? data.service.history.at(-1)?.title : action.startsWith('offer-') ? data.offer.history.at(-1)?.title : action.startsWith('lab-') ? data.lab.history.at(-1)?.title : data.history.at(-1)?.title) || 'Acțiune înregistrată.' : 'Demonstrația a revenit la starea inițială.');
      if (!action) { setTab('work'); setView('overview'); setMobileNav(false); }
      return true;
    } catch (e) {
      let message = e instanceof Error ? e.message : 'Conexiunea locală a fost întreruptă. Reîncearcă.';
      try {
        const refreshed = await fetch('/api/state');
        if (refreshed.ok) { setState(await refreshed.json()); setPanel(null); message += ' Dosarul a fost resincronizat; verifică starea curentă.'; }
      } catch { /* Keep the last confirmed state if the API is unavailable. */ }
      setError(message);
      return false;
    } finally { setBusy(false); }
  }
  const docs = state ? getDocuments(state) : [];
  const mainDocs = docs.slice(0,6);
  const openDoc = (id: string) => setPanel({ kind: 'document', id });
  const openDossier = () => { setView('dossier'); setTab('work'); setMobileNav(false); };
  const openService = () => { setView('service'); setMobileNav(false); };
  const openOffer = () => { setView('offer'); setMobileNav(false); };
  const openLab = () => { setView('lab'); setMobileNav(false); };
  const stageIndex = state ? stageOrder.indexOf(state.stage) : 0;
  const copy = state ? workCopy[state.stage] : workCopy.change;
  const CopyIcon = copy.icon;
  const packageReady = !!state?.attachments.test && state?.attachments.manualRevision === 2 && state?.observation?.status === 'closed';
  const readyCount = 1 + Number(stageIndex >= 2) + Number(state?.attachments.test) + Number(state?.attachments.manualRevision === 2) + Number(state?.observation?.status === 'closed');
  const currentDoc = panel?.kind === 'document' ? docs.find(d => d.id === panel.id) : null;
  const selectedAction = panel?.kind === 'action' ? panel.action : null;

  function PackageChecklist({ full = false }: { full?: boolean }) {
    if (!state) return null;
    const rows = [
      { label: 'Borderou de documente', detail: `Reviziile curente sunt identificate`, ok: true, doc: 'register' },
      { label: 'Documentația lucrării', detail: `Rev. 0${state.revision} · ${stageIndex >= 2 ? 'Implementare consemnată' : 'Implementare necesară'}`, ok: stageIndex >= 2, doc: 'requirements' },
      { label: 'Fișă de test finală', detail: state.attachments.test ? 'Rev. 02 atașată' : 'Lipsește din pachet', ok: state.attachments.test, doc: 'test', action: 'attach-test' as Action },
      { label: 'Instrucțiuni operator', detail: state.attachments.manualRevision === 2 ? 'Rev. 02 atașată' : 'Pachetul conține rev. 01', ok: state.attachments.manualRevision === 2, doc: 'manual', action: 'attach-manual' as Action },
      { label: 'Observații închise', detail: state.observation?.status === 'closed' ? 'Retestare confirmată' : state.observation ? 'Retestare necesară' : 'Testarea urmează', ok: state.observation?.status === 'closed', doc: 'test' },
    ];
    return <div className={`package-list ${full ? 'full' : ''}`}>{rows.map((r,i) => <div className="package-row" key={r.label}><span className={`check-dot ${r.ok ? 'checked' : ''}`}>{r.ok ? <Check size={12}/> : <span/>}</span><button className="package-label" onClick={() => openDoc(r.doc)}><strong>{r.label}</strong><small className={!r.ok && i > 1 ? 'pending-text' : ''}>{r.detail}</small></button>{full && r.action && !r.ok && state.stage === 'preparation' && <button className="button small-button secondary" disabled={busy} onClick={() => void mutate(r.action)}><Plus size={14}/>Atașează</button>}{full && r.ok && <span className="complete-word">Pregătit</span>}</div>)}</div>;
  }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'is-open' : ''}`}>
      <button className="brand" onClick={() => { setView('overview'); setMobileNav(false); }} aria-label="ICPE Bistrița, vedere de ansamblu"><img src="/logo.png" alt="Sigla ICPE Bistrița"/><span><strong>ICPE <b>Bistrița</b></strong><small>SPAȚIU DE LUCRU · DEMO</small></span></button>
      <div className="workspace-name"><span className="workspace-icon"><Layers3 size={17}/></span><div><strong>Fluxuri de lucru</strong><small>Concept interactiv</small></div><span className="version-tag">v.04</span></div>
      <p className="nav-label">ORGANIZARE</p>
      <nav><button className={`nav-item ${view === 'overview' ? 'active' : ''}`} onClick={() => { setView('overview'); setMobileNav(false); }}><FolderClosed size={18}/>Scenarii<span className="nav-count">04</span></button><button className="nav-item" onClick={() => { setPanel({kind:'help'}); setMobileNav(false); }}><CircleHelp size={18}/>Ajutor<ArrowUpRight size={14} className="nav-arrow"/></button></nav>
      <div className="sidebar-project"><p className="nav-label">SCENARII DEMONSTRATIVE</p><button onClick={openOffer} className={view === 'offer' ? 'selected-project' : ''}><span className="project-indicator"/><span>Solicitare și ofertă<small>DEMO-SOL-001 · Ofertare</small></span><ChevronRight size={15}/></button><button onClick={openDossier} className={view === 'dossier' ? 'selected-project' : ''}><span className="project-indicator"/><span>Colibița<small>DEMO-L-001 · Lucrare</small></span><ChevronRight size={15}/></button><button onClick={openLab} className={view === 'lab' ? 'selected-project' : ''}><span className="project-indicator"/><span>Probă și raport<small>DEMO-LAB-001 · Laborator</small></span><ChevronRight size={15}/></button><button onClick={openService} className={view === 'service' ? 'selected-project' : ''}><span className="project-indicator"/><span>Intervenție după predare<small>DEMO-SRV-001 · Sesizare</small></span><ChevronRight size={15}/></button></div>
      <div className="sidebar-bottom"><div className="idea-mark"><span>i</span><p>Un punct de pornire<br/><strong>pentru o discuție.</strong></p></div><p className="small muted">Patru exemple fictive de fluxuri pe care le putem discuta împreună.</p><button className="reset-button" onClick={() => setPanel({kind:'reset'})} disabled={!state || busy}><RotateCcw size={15}/>Resetează demonstrația</button><div className="local-status"><span/>Sesiune locală<span className="mono">DEMO</span></div></div>
    </aside>
    {mobileNav && <button className="nav-backdrop" onClick={() => setMobileNav(false)} aria-label="Închide navigarea"/>}
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Deschide navigarea"><Menu size={21}/></button><span className="breadcrumb-home">Spațiu de lucru</span><ChevronRight size={13}/><button onClick={() => setView('overview')}>Scenarii</button>{view !== 'overview' && <><ChevronRight size={13}/><span className="breadcrumb-current">{view === 'dossier' ? 'DEMO-L-001' : view === 'service' ? 'DEMO-SRV-001' : view === 'offer' ? 'DEMO-SOL-001' : 'DEMO-LAB-001'}</span></>}</div><span className="demo-banner"><span/>PoC pentru discuție <b>•</b> Date și proceduri fictive</span></header>
      <main>
        {error && !panel && <div className="error-box" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={() => void load()}>Reîncearcă</button></div>}
        {!state ? <div className="loading-state">{!error && <LoaderCircle className="spin"/>}<h2>{error ? 'Dosarul nu este disponibil momentan.' : 'Deschidem spațiul de lucru…'}</h2></div> : view === 'overview' ? <>
          <div className="page-heading overview-heading"><div><p className="eyebrow"><span className="red-line"/>DE LA SOLICITARE LA INTERVENȚIE</p><h1>Patru trasee.<br/><span>Pași vizibili.</span></h1><p className="page-description">Ofertare, coordonarea lucrării, analiza unei probe și intervenția după predare.<br className="desktop-br"/> Explorează posibile moduri de lucru, pas cu pas.</p></div><div className="overview-note"><span className="note-symbol">↗</span><p>O idee de explorat.<br/><strong>Împreună cu echipa.</strong></p></div></div>
          <div className="section-heading"><h2>Scenarii <span>04</span></h2><span className="small muted">Patru fluxuri interactive, cu date fictive.</span></div>
          <article className="featured-project"><div className="featured-content"><div className="project-topline"><span className="mono">DEMO-L-001</span><Badge tone={state.stage === 'delivered' ? 'green' : 'red'}>{stageNames[state.stage]}</Badge></div><p className="eyebrow project-category">TRATAREA APEI / AUTOMATIZARE</p><h2>Stația de apă<br/>Colibița</h2><p>Un tablou de automatizare. O schimbare de cerință.<br/>Întregul traseu, până la predarea documentelor.</p><div className="project-meta"><span><FolderOpen size={15}/>6 documente de referință</span><span><Clock3 size={15}/>~5 min de explorat</span></div><button className="button primary" onClick={openDossier}>{state.stage === 'change' ? 'Explorează dosarul' : 'Continuă în dosar'}<ArrowRight size={17}/></button></div><CabinetIllustration revision={state.revision}/><div className="featured-footer"><span><span className="live-dot"/>SCENARIU INTERACTIV</span><span>De la modificare la predare <ArrowUpRight size={15}/></span></div></article>
          <article className="service-preview offer-preview"><span className="service-preview-icon"><ClipboardCheck size={25}/></span><div><span className="mono">DEMO-SOL-001 · ÎNAINTEA LUCRĂRII</span><h2>De la cerere la pornire.</h2><p>Clarificări, două versiuni de ofertă, decizia fictivă a clientului și fișa transmisă echipei lucrării. Scenariul poate fi parcurs independent.</p><div className="service-preview-meta"><span><Link2 size={14}/>Stația fictivă Orizont</span><span><Clock3 size={14}/>~4 min de explorat</span></div></div><div className="service-preview-action"><Badge tone={state.offer.stage === 'started' ? 'green' : 'amber'}>{state.offer.stage === 'started' ? 'Pornită' : 'Interactiv'}</Badge><button className="button secondary" onClick={openOffer}>{state.offer.stage === 'received' ? 'Explorează ofertarea' : 'Continuă ofertarea'}<ArrowRight size={16}/></button></div></article>
          <article className="service-preview lab-preview"><span className="service-preview-icon"><FlaskConical size={25}/></span><div><span className="mono">DEMO-LAB-001 · LABORATOR</span><h2>O probă. Un raport urmărit.</h2><p>Recoltare, primire, rezultate fictive, verificare separată și raport demonstrativ. Identificatorul probei leagă toate înregistrările.</p><div className="service-preview-meta"><span><Link2 size={14}/>Punct de recoltare fictiv · stația Nord</span><span><Clock3 size={14}/>~3 min de explorat</span></div></div><div className="service-preview-action"><Badge tone={state.lab.stage === 'issued' ? 'green' : 'amber'}>{state.lab.stage === 'issued' ? 'Emis' : 'Interactiv'}</Badge><button className="button secondary" onClick={openLab}>{state.lab.stage === 'requested' ? 'Explorează laboratorul' : 'Continuă laboratorul'}<ArrowRight size={16}/></button></div></article>
          <article className="service-preview"><span className="service-preview-icon"><Wrench size={25}/></span><div><span className="mono">DEMO-SRV-001 · DUPĂ PREDARE</span><h2>O sesizare. Un traseu clar.</h2><p>Mesajul beneficiarului, programarea, intervenția, verificarea și confirmarea. Un scenariu pe care îl poți parcurge independent.</p><div className="service-preview-meta"><span><Link2 size={14}/>Predare anterioară fictivă: DEMO-PV-002</span><span><Clock3 size={14}/>~3 min de explorat</span></div></div><div className="service-preview-action"><Badge tone={state.service.stage === 'closed' ? 'green' : 'amber'}>{state.service.stage === 'closed' ? 'Închisă' : 'Interactiv'}</Badge><button className="button secondary" onClick={openService}>{state.service.stage === 'reported' ? 'Explorează intervenția' : 'Continuă intervenția'}<ArrowRight size={16}/></button></div></article>
          <footer className="overview-footer"><span><Link2 size={15}/>Patru exemple fictive pentru fluxuri diferite din jurul unei lucrări.</span><button onClick={() => setPanel({kind:'help'})}>Ajutor <ArrowUpRight size={15}/></button></footer>
        </> : view === 'service' ? <ServiceScenario service={state.service} busy={busy} onAction={mutate} onBack={() => setView('overview')}/> : view === 'offer' ? <OfferScenario offer={state.offer} busy={busy} onAction={mutate} onBack={() => setView('overview')}/> : view === 'lab' ? <LabScenario lab={state.lab} busy={busy} onAction={mutate} onBack={() => setView('overview')}/> : <>
          <div className="dossier-heading"><div><button className="back-link" onClick={() => setView('overview')}><ArrowLeft size={14}/>Toate scenariile</button><div className="dossier-code"><span className="mono">DEMO-L-001</span><span>/</span><span>TABLOU DE AUTOMATIZARE</span></div><h1>Stația de apă Colibița<span className="title-dot">.</span></h1><p className="page-description">Un singur loc pentru documente, schimbări și pașii până la predare.</p></div><Badge tone={state.stage === 'delivered' ? 'green' : 'red'}>{stageNames[state.stage]}</Badge></div>
          <div className="dossier-metadata"><div><small>BENEFICIAR FICTIV</small><strong>Operator Apă Exemplu</strong></div><div><small>ECHIPAMENT</small><strong className="mono">DEMO-TA-001</strong></div><div><small>REVIZIA CERINȚELOR</small><button onClick={() => openDoc('requirements')}>Revizia 0{state.revision}<ExternalLink size={12}/></button></div><div><small>COORDONARE</small><strong>Rol demonstrativ</strong></div></div>
          <div className="flow-container"><div className="flow-heading"><span className="eyebrow">PARCURSUL LUCRĂRII</span><span className="small muted">{state.stage === 'delivered' ? 'Traseu demonstrativ încheiat' : 'Fiecare pas păstrează legătura cu cel anterior'}</span></div><ol className="process-flow">{['Deschidere','Proiectare','Modificare','Execuție','Testare','Remediere & retestare','Pregătire predare','Predare'].map((name,i) => { const current = [2,3,4,5,5,6,7][stageIndex]; const done = i < current || state.stage === 'delivered'; return <li className={`${done ? 'done' : ''} ${i === current && !done ? 'current' : ''}`} key={name}><span className="flow-node">{done ? <Check size={14}/> : String(i+1).padStart(2,'0')}</span><span className="flow-name">{name}</span>{i===current && !done && <small>ÎN CURS</small>}</li>; })}</ol></div>
          <div className="tabs" role="tablist" aria-label="Secțiuni dosar"><button role="tab" aria-selected={tab==='work'} className={tab==='work'?'active':''} onClick={() => setTab('work')}><Layers3 size={16}/>Spațiu de lucru</button><button role="tab" aria-selected={tab==='documents'} className={tab==='documents'?'active':''} onClick={() => setTab('documents')}><FileText size={16}/>Documente<span>{mainDocs.length}</span></button><button role="tab" aria-selected={tab==='history'} className={tab==='history'?'active':''} onClick={() => setTab('history')}><History size={16}/>Istoric<span>{state.history.length}</span></button><span className="saved-status"><span/>Salvat local</span></div>
          {tab === 'work' && <div className="work-layout"><div className="work-main"><section className={`next-action ${state.stage === 'delivered' ? 'finished' : ''}`} key={state.stage}><div className="action-eyebrow"><span className="eyebrow">{copy.eyebrow}</span><CopyIcon size={22} strokeWidth={1.5}/></div><h2>{copy.title}</h2><p>{copy.text}</p>{state.stage === 'change' && <div className="change-preview"><span className="mini-file"><FileText size={18}/></span><div><strong>Solicitare de modificare</strong><span>DEMO-MOD-001 · 05 oct. 2026, dată fictivă</span></div><span className="revision-route">01<ArrowRight size={14}/>02</span></div>}{state.stage === 'implementation' && <div className="inline-task"><span className="task-avatar">C</span><div><strong>Actualizează denumirile interfeței</strong><span>Persoana C · Rol demonstrativ · Termen fictiv: 08.10.2026</span></div><Badge tone="amber">De realizat</Badge></div>}{state.observation && state.stage !== 'delivered' && <div className="observation-link"><AlertCircle size={16}/><button onClick={() => openDoc('test')}>DEMO-OBS-001</button><Badge tone={state.observation.status==='closed'?'green':'amber'}>{state.observation.status==='closed'?'Închisă prin retestare':state.observation.status==='awaiting-retest'?'De retestat':'Deschisă'}</Badge></div>}{state.stage === 'retesting' && <Evidence/>}{state.stage === 'preparation' ? <><PackageChecklist full/>{packageReady ? <button className="button primary" onClick={() => setPanel({kind:'action',action:'handover'})}>Pregătește predarea<ArrowRight size={16}/></button> : <p className="action-footnote"><Link2 size={13}/>Atașează cele două documente pentru a continua la predare.</p>}</> : <button className={`button ${state.stage==='delivered'?'dark':'primary'}`} onClick={() => copy.action ? setPanel({kind:'action',action:copy.action}) : openDoc('handover-record')}>{copy.button}<ArrowRight size={16}/></button>}{state.stage === 'delivered' && <div className="delivered-stamp"><ShieldCheck size={18}/><div><strong>{state.deliveredPackage?.id}</strong><span>Reviziile transmise sunt păstrate în pachet.</span></div></div>}</section>
            <section className="linked-section"><div className="section-heading"><h2>La îndemână</h2><button className="text-button" onClick={() => setTab('documents')}>Toate documentele<ArrowRight size={14}/></button></div><div className="linked-documents">{[{id:'requirements',title:'Cerințe de afișare',sub:`DEMO-CER-001 · rev. 0${state.revision}`},{id:'change',title:'Cerere de modificare',sub:'DEMO-MOD-001 · rev. 01'},{id:'test',title:'Fișă de test & observație',sub:`DEMO-TEST-001 · rev. 0${state.revision}`}].map(d => <button key={d.id} className="linked-document" onClick={() => openDoc(d.id)}><FileText size={19} strokeWidth={1.5}/><div><strong>{d.title}</strong><span>{d.sub}</span></div><ArrowUpRight size={16}/></button>)}</div></section>
            <div className="trace-strip"><Link2 size={17}/><span>Modificare</span><ArrowRight size={12}/><span>Revizie</span><ArrowRight size={12}/><span>Sarcină</span><ArrowRight size={12}/><span>Test</span><ArrowRight size={12}/><span>Predare</span></div>
          </div><aside className="dossier-aside"><section className="package-card"><div className="section-heading"><h2>Pachet de predare</h2><PackageCheck size={19}/></div><div className="package-progress"><strong>{readyCount}<span>/5</span></strong><span>condiții îndeplinite</span><Badge tone={packageReady?'green':'amber'}>{state.stage==='delivered'?'Predat':packageReady?'Pregătit':'În pregătire'}</Badge></div><div className="segmented-progress">{Array.from({length:5},(_,i)=><span key={i} className={i<readyCount?'filled':''}/>)}</div><PackageChecklist/><button className="package-footer" onClick={() => openDoc('handover-list')}>Deschide lista de predare<ArrowUpRight size={15}/></button></section><section className="recent-history"><div className="section-heading"><h2>Ultima activitate</h2><Clock3 size={16}/></div>{[...state.history].reverse().slice(0,3).map((h,i) => <div className="history-mini" key={h.id}><span className={`history-point ${i===0?'latest':''}`}/><div><strong>{h.title}</strong><p>{h.detail}</p><time>{formatDate(h.at)} · {formatTime(h.at)}</time></div></div>)}<button className="text-button" onClick={() => setTab('history')}>Vezi întregul istoric<ArrowRight size={14}/></button></section></aside></div>}
          {tab === 'documents' && <div className="documents-tab"><div className="section-heading"><div><h2>Documentele dosarului</h2><p className="small muted">Cele șase documente din scenariu, actualizate pe măsură ce parcurgi demonstrația.</p></div><button className="button secondary" onClick={() => setPanel({kind:'compare'})}><GitCompareArrows size={16}/>Compară cerințele</button></div><div className="document-list">{mainDocs.map((doc,i) => <button className="document-row" key={doc.id} onClick={() => openDoc(doc.id)}><span className="doc-number">0{i+1}</span><span className="doc-icon"><FileText size={22} strokeWidth={1.4}/></span><span className="doc-row-title"><strong>{doc.title}</strong><small>{doc.code}</small></span><span className="doc-revision">rev. {doc.revision}</span><span className="doc-state">{doc.status}</span><ArrowUpRight size={17}/></button>)}</div><div className="support-heading"><h3>Referințe asociate</h3><p>Extrase fictive pentru a urmări reviziile și legăturile dintre documente.</p></div><div className="support-docs">{docs.slice(6).map(doc=><button key={doc.id} onClick={()=>openDoc(doc.id)}><Layers3 size={21}/><strong>{doc.title}</strong><span>{doc.code} · rev. {doc.revision}</span><ArrowUpRight size={16}/></button>)}</div></div>}
          {tab === 'history' && <section className="history-tab"><div className="section-heading"><div><h2>Firul lucrării</h2><p className="small muted">Pașii inițiali sunt fictivi; acțiunile tale păstrează ora înregistrării locale.</p></div><Badge>{state.history.length} înregistrări</Badge></div><div className="timeline">{[...state.history].reverse().map((h,i)=><article key={h.id}><div className="timeline-date"><time>{formatDate(h.at)}</time><span>{formatTime(h.at)}</span></div><span className={`timeline-point ${i===0?'latest':''}`}><Check size={12}/></span><div><span className="mono">{h.id}</span><h3>{h.title}</h3><p>{h.detail}</p></div></article>)}</div></section>}
          <footer className="dossier-footer"><span>DEMO-L-001 · Exclusiv date fictive</span><button onClick={() => setPanel({kind:'help'})}><CircleHelp size={14}/>Ajutor</button></footer>
        </>}
      </main>
    </div>
    {toast && <div className="toast" role="status"><CheckCircle2 size={18}/>{toast}<button aria-label="Închide notificarea" onClick={() => setToast('')}><X size={15}/></button></div>}
    {panel && <Modal onClose={() => { if (!busy) { setPanel(null); setError(''); } }} wide={panel.kind==='document'||panel.kind==='compare'||selectedAction==='accept-change'} eyebrow={panel.kind==='document' ? 'DOSAR DEMO-L-001 / DOCUMENT' : panel.kind==='help' ? 'GHID RAPID' : panel.kind==='reset' ? 'SESIUNE DEMONSTRATIVĂ' : 'DOSAR DEMO-L-001 / SIMULARE'} title={currentDoc?.title || (selectedAction ? actionTitles[selectedAction] : panel.kind==='compare'?'Ce se schimbă în revizia 02':panel.kind==='help'?'Ajutor':'Reîncepem demonstrația?')}>
      {error && <div className="error-box modal-error" role="alert"><AlertCircle size={18}/>{error}</div>}
      {currentDoc && state && <DocumentViewer doc={currentDoc} state={state} openCompare={() => setPanel({kind:'compare'})}/>}
      {panel.kind==='compare' && state && <div className="modal-content"><p className="modal-intro">Cerințe de afișare · <span className="mono">DEMO-CER-001</span>. Comparație simplificată a extraselor fictive.</p><RevisionComparison accepted={state.revision===2}/><div className="info-callout"><Link2 size={18}/><p>Schimbarea afectează cerințele, lista semnalelor și fișa de test. Revizia 01 rămâne consultabilă ca versiune anterioară.</p></div>{state.stage==='change' && <div className="modal-actions"><button className="button primary" onClick={()=>setPanel({kind:'action',action:'accept-change'})}>Analizează decizia<ArrowRight size={16}/></button></div>}</div>}
      {selectedAction && state && <div className="modal-content">
        {selectedAction==='accept-change' && <><div className="request-context"><span className="request-avatar">BE</span><div><strong>Operator Apă Exemplu</strong><span>Beneficiar fictiv · Cerere DEMO-MOD-001</span></div><Badge tone="amber">De analizat</Badge></div><p className="modal-intro">„Dorim afișarea distinctă a stărilor Funcționare și Indisponibil pentru echipamentul P-01.”</p><RevisionComparison accepted={false}/><h3 className="minor-heading">Ce produce această decizie</h3><ul className="effect-list"><li><Check size={15}/>Cerințele, semnalele și lista testelor trec la revizia 02.</li><li><Check size={15}/>Se creează sarcina de implementare pentru Persoana C.</li><li><Check size={15}/>Decizia și reviziile sunt păstrate în istoricul dosarului.</li></ul><div className="info-callout"><ShieldCheck size={18}/><p>Evaluarea tehnică este presupusă efectuată în scenariul fictiv. Acest click înregistrează o decizie demonstrativă, fără valoare de semnătură.</p></div></>}
        {selectedAction==='implement' && <><p className="modal-intro">Consemnează executarea sarcinii demonstrative pentru denumirile interfeței operatorului.</p><div className="form-summary"><div><span>Responsabil</span><strong>Persoana C · Rol demonstrativ</strong></div><div><span>Referință de implementare</span><strong>DEMO-CER-001 / rev. 02</strong></div><div><span>Elemente asociate</span><strong>Lista semnalelor și instrucțiunile operatorului</strong></div></div><div className="info-callout"><Link2 size={18}/><p>Instrucțiunile rev. 02 devin disponibile pentru verificare. Atașarea lor în pachetul de predare va fi un pas separat. Testul va verifica rezultatul implementării.</p></div></>}
        {selectedAction==='run-test' && <><p className="modal-intro">Rezultate precompletate pentru demonstrație. Nu reprezintă teste efectuate asupra unui echipament real.</p><div className="test-result warning"><AlertCircle size={20}/><div><h3>Corespondența etichetelor</h3><p>Se așteaptă „Indisponibil”, dar interfața afișează încă „Oprit”.</p><span>Referință: DEMO-CER-001 · rev. 02</span></div><Badge tone="amber">Observație</Badge></div><div className="test-result success"><CheckCircle2 size={20}/><div><h3>Instrucțiunile operatorului</h3><p>Denumirile din DEMO-MAN-001 rev. 02 corespund cerințelor.</p></div></div><div className="info-callout"><Link2 size={18}/><p>Înregistrarea păstrează ambele rezultate și deschide DEMO-OBS-001 pentru Persoana C. Predarea rămâne condiționată de remediere și retestare.</p></div></>}
        {selectedAction==='remediate' && <><p className="modal-intro">Denumirea anterioară a fost înlocuită în simulare. Se consemnează remedierea și dovada demonstrativă de mai jos.</p><Evidence/><div className="form-summary"><div><span>Observație</span><strong>DEMO-OBS-001</strong></div><div><span>Responsabil remediere</span><strong>Persoana C · Rol demonstrativ</strong></div><div><span>Starea după înregistrare</span><strong>Remediată · De retestat</strong></div></div><div className="info-callout"><Clock3 size={18}/><p>Observația se va închide doar după confirmarea retestării.</p></div></>}
        {selectedAction==='retest' && <><p className="modal-intro">Persoana D, verificator demonstrativ, confirmă denumirea actualizată față de cerințele acceptate.</p><Evidence/><div className="test-result success"><CheckCircle2 size={20}/><div><h3>Denumirile corespund reviziei 02</h3><p>Rezultat demonstrativ: corespondență confirmată. Observația DEMO-OBS-001 poate fi închisă.</p></div></div><p className="small muted">Rezultatul inițial rămâne în fișa de test alături de retestare.</p></>}
        {selectedAction==='handover' && <><p className="modal-intro">Toate condițiile demonstrative sunt îndeplinite. Acțiunea va păstra lista reviziilor transmise și va emite procesul-verbal fictiv.</p><PackageChecklist full/><div className="info-callout"><ShieldCheck size={18}/><p>Predat de: rol demonstrativ coordonator. Primit de: rol demonstrativ beneficiar. Confirmarea nu reprezintă recepție tehnică sau semnătură juridică.</p></div></>}
        <div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setPanel(null)}>Înapoi la dosar</button><button className="button primary" disabled={busy} onClick={()=>void mutate(selectedAction)}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {actionTitles[selectedAction]}</button></div><p className="modal-disclaimer">PoC pentru discuție • Date și proceduri fictive</p>
      </div>}
      {panel.kind==='reset' && <div className="modal-content"><p className="modal-intro">Toate cele patru scenarii revin la starea inițială. Acțiunile sesiunii, ofertele, analiza simulată, predarea și intervenția sunt eliminate; evenimentele fictive inițiale se restaurează.</p><div className="info-callout"><RotateCcw size={18}/><p>Datele seed se păstrează. Poți parcurge din nou fiecare traseu.</p></div><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setPanel(null)}>Păstrează sesiunea</button><button className="button primary" disabled={busy} onClick={()=>void mutate()}>{busy?<LoaderCircle className="spin" size={16}/>:<RotateCcw size={16}/>}Resetează acum</button></div></div>}
      {panel.kind==='help' && <HelpSection dossierAvailable={!!state} onOpenDossier={()=>{setPanel(null);openDossier();}} onOpenService={()=>{setPanel(null);openService();}} onOpenOffer={()=>{setPanel(null);openOffer();}} onOpenLab={()=>{setPanel(null);openLab();}}/>}
    </Modal>}
  </div>;
}


